apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: prod-payments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: finserv-registry.internal/payments/payment-gateway:v1.0.0
          ports:
            - containerPort: 8443
