apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: prod-payments
  labels:
    security.finserv.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
